# -*- coding: utf-8 -*-
ENUMA_ELISH = [
{
 "files": ["01_Tablilla_del_Enuma_Elish_Biblioteca_de_Asurbanipal_650aC.jpg"],
 "views": ["Tablilla del Enuma Elish — Biblioteca de Asurbanipal, Nínive (s. VII a.C.)"],
 "title": "«Cuando en lo alto»: el poema en la biblioteca de Nínive",
 "artist": "Biblioteca de Asurbanipal, Nínive (668-631 a.C.)",
 "meta": "Arcilla con escritura cuneiforme, fragmentos unidos | British Museum, Londres (K.3473)",
 "wikiUrl": "https://es.wikipedia.org/wiki/En%C3%BAma_Elish",
 "snippet": "Una columna de arcilla recompuesta a partir de tres pedazos, con el poema que Babilonia recitaba cada año para recordar cómo su dios había hecho el mundo.",
 "analysis": "El poema toma su nombre de sus dos primeras palabras, enūma eliš, «cuando en lo alto»: cuando en lo alto el cielo no tenía nombre y abajo la tierra tampoco, solo existían Apsu, el agua dulce, y Tiamat, el agua salada, mezclando sus aguas. De ellos nacen los dioses, cuyo alboroto no deja descansar a Apsu —el mismo motivo del ruido que desencadena el Diluvio en el Atrahasis—. Ea mata a Apsu; Tiamat reúne un ejército de once monstruos al mando de Qingu, y los dioses, aterrados, buscan un campeón. Marduk acepta a cambio de la soberanía, parte a Tiamat en dos «como un pescado para secar», hace el cielo con una mitad y la tierra con la otra, y crea a los hombres con la sangre de Qingu para que trabajen en lugar de los dioses. El poema termina con los cincuenta nombres de Marduk. Según la edición de L. W. King, este fragmento pertenece a la tablilla III, la que repite casi palabra por palabra el relato de cómo Tiamat arma a sus monstruos a medida que los mensajeros lo llevan de un dios a otro.",
 "history": "George Smith, el mismo que leyó el Diluvio en la tablilla XI de Gilgamesh, identificó los primeros fragmentos del poema en el British Museum y los publicó en 1876 en The Chaldean Account of Genesis. Leonard William King reunió en 1902 todo lo que se conocía en The Seven Tablets of Creation, y a lo largo del siglo XX aparecieron copias en Assur, Kish, Sultantepe y Sippar hasta completar casi entero el texto. La comparación con el primer capítulo del Génesis fue inmediata —las aguas primordiales, la separación de las aguas de arriba y de abajo, el orden de la creación— y alimentó durante décadas la polémica «Babel und Bibel».",
 "bio": "Asurbanipal, rey de Asiria entre 668 y c. 631 a.C., se preciaba de saber leer y escribir, cosa rara en un rey, y mandó copiar o requisar tablillas de todos los templos de su imperio para su biblioteca de Nínive. Cuando la ciudad cayó en 612 a.C. el fuego coció la arcilla, y así se conservaron decenas de miles de tablillas y fragmentos que hoy están casi todos en el British Museum."
},
{
 "files": ["02_Tablilla_del_Enuma_Elish_de_Kish_Ashmolean.jpg"],
 "views": ["Tablilla del Enuma Elish hallada en Kish — Ashmolean Museum, Oxford"],
 "title": "La copia de Kish",
 "artist": "Kish, montículo W, periodo neoasirio (c. 700 a.C.)",
 "meta": "Arcilla con escritura cuneiforme | Ashmolean Museum, Oxford (AN1926.373)",
 "wikiUrl": "https://es.wikipedia.org/wiki/Kish_(Sumeria)",
 "snippet": "El mismo poema, copiado lejos de Nínive: la prueba de que el Enuma Elish no era una rareza de biblioteca real sino un texto que se aprendía en las escuelas.",
 "analysis": "Es una tablilla alta y estrecha, con la superficie muy gastada pero con las columnas de signos todavía reconocibles. Su valor no está en el aspecto sino en el lugar del hallazgo. Las copias de Nínive salen de una biblioteca real hecha por encargo; las de Kish, como las de Sultantepe o Sippar, muestran que el poema se copiaba en otras ciudades y en otros ambientes. Las variantes entre copias han servido además para reconstruir los versos perdidos y para fechar el poema, que muchos especialistas sitúan en el siglo XII a.C., cuando la estatua de Marduk volvió a Babilonia desde Elam en tiempos de Nabucodonosor I.",
 "history": "Kish, a unos quince kilómetros al este de Babilonia, fue excavada entre 1923 y 1933 por una expedición conjunta de la Universidad de Oxford y el Field Museum de Chicago, en la que Stephen Langdon —el mismo que publicó la Lista Real Sumeria— se ocupó de los textos. El reparto de los hallazgos entre las instituciones participantes trajo esta tablilla a Oxford, donde se inventarió en 1926.",
 "bio": "Kish fue, según la Lista Real Sumeria, la primera ciudad que recibió la realeza después del Diluvio, y durante siglos «rey de Kish» fue un título de dominio sobre todo el país. En el primer milenio era ya una ciudad menor a la sombra de Babilonia, pero conservó sus templos y sus escribas."
},
{
 "files": ["03_Mushhushshu_Dragon_de_Marduk_Puerta_de_Ishtar_575aC.jpg"],
 "views": ["Mušḫuššu, el dragón de Marduk — Puerta de Ishtar de Babilonia (s. VI a.C.)"],
 "title": "El mušḫuššu, el dragón de Marduk",
 "artist": "Puerta de Ishtar, Babilonia, reinado de Nabucodonosor II (604-562 a.C.)",
 "meta": "Ladrillo moldeado y vidriado | Museo de Pérgamo, Berlín",
 "wikiUrl": "https://es.wikipedia.org/wiki/Mu%C5%A1hu%C5%A1%C5%A1u",
 "snippet": "Cabeza de serpiente, patas delanteras de león, traseras de ave y cola de escorpión. Fue uno de los monstruos de Tiamat, y acabó siendo el animal del dios que la venció.",
 "analysis": "El mušḫuššu —«serpiente furiosa»— avanza de perfil sobre el fondo azul vidriado: cuerpo escamoso, cuello largo, cuerno sobre la cabeza, lengua bífida, patas delanteras de felino y traseras con garras de ave. En el Enuma Elish figura entre los once monstruos que Tiamat engendra para su guerra contra los dioses. Tras la victoria, Marduk no los destruye: los apresa, y según la tablilla V pone sus imágenes a la puerta del Apsu como recuerdo. El monstruo vencido pasa así a ser el emblema del vencedor, y en el siglo VI a.C. los dragones de Marduk alternaban con los toros de Adad en la puerta junto a la que pasaba la procesión del Año Nuevo, la fiesta en la que se recitaba el poema.",
 "history": "La Puerta de Ishtar fue excavada por Robert Koldewey en la gran campaña alemana en Babilonia de 1899-1917. Los ladrillos vidriados, rotos en decenas de miles de fragmentos, se enviaron a Berlín, donde se desalaron y se reconstruyeron pieza a pieza; la puerta se montó en el Museo de Pérgamo en 1930. Paneles sueltos de animales como este se repartieron después entre museos de todo el mundo.",
 "bio": "Nabucodonosor II, el rey que tomó Jerusalén en 587 a.C. y deportó a su élite a Babilonia, reconstruyó la ciudad como capital del mundo: la Vía Procesional, la Puerta de Ishtar, el Esagila y el zigurat Etemenanki, la Torre de Babel de la tradición. Los desterrados de Judá vieron esos dragones, y buena parte de los especialistas lee Génesis 1 como una respuesta a la teología que representaban."
},
{
 "files": ["04_Sello_del_Culto_de_Marduk_y_Nabu_Neoasirio.jpg"],
 "views": ["Sello cilíndrico y su impresión en arcilla, con el culto de Marduk y Nabu — periodo neoasirio"],
 "title": "Los símbolos de Marduk en un sello",
 "artist": "Mesopotamia, periodo neoasirio (c. 900-600 a.C.)",
 "meta": "Sello cilíndrico de calcedonia | Museo del Louvre, París (AO 7217)",
 "wikiUrl": "https://es.wikipedia.org/wiki/Marduk",
 "snippet": "Un cilindro de piedra de pocos centímetros con el culto de Marduk y de su hijo Nabu: el poema de la creación reducido a sus emblemas.",
 "analysis": "El Louvre expone el cilindro junto a una impresión moderna en arcilla, que es como había que verlo: los sellos se hacían rodar sobre el barro húmedo para firmar, y la imagen grabada era a la vez firma y amuleto. La escena desplegada es un pequeño panteón. Un dios se yergue sobre el lomo del mušḫuššu, el dragón que había sido uno de los monstruos de Tiamat; junto a él, sobre otro dragón, se alza la marru, la azada triangular de Marduk, y más allá el cálamo de Nabu, su hijo, dios de la escritura. Arriba flotan el disco alado, la media luna, las estrellas y los siete puntos de los Sebettu, y a los extremos dos orantes levantan la mano. Todo el desenlace del Enuma Elish está en la composición: el monstruo del caos convertido en peana del dios que lo venció, y los astros en el lugar que Marduk les asignó en la tablilla V.",
 "history": "En el primer milenio Nabu fue ganando terreno a su padre hasta casi igualarlo: en la fiesta del Año Nuevo su estatua viajaba desde Borsippa a Babilonia para acompañar a la de Marduk. Los sellos con sus dos emblemas juntos son muy frecuentes en época neoasiria y neobabilónica, y muestran hasta qué punto la teología del Enuma Elish había pasado a la religión cotidiana.",
 "bio": "La calcedonia, una piedra dura y translúcida, se trabajaba con taladros de arco y abrasivos; tallar un sello así era oficio de especialista, y el objeto, un bien de prestigio que se llevaba colgado y a menudo se enterraba con su dueño."
},
{
 "files": ["05_Ritual_del_Akitu_Ano_Nuevo_de_Babilonia.jpg"],
 "views": ["Tablilla del ritual del Año Nuevo (akītu) de Babilonia — Museo del Louvre"],
 "title": "El ritual del Año Nuevo, donde se recitaba el poema",
 "artist": "Babilonia, copia de época seléucida (c. 300-100 a.C.)",
 "meta": "Arcilla con escritura cuneiforme | Museo del Louvre, París (MNB 1848)",
 "wikiUrl": "https://es.wikipedia.org/wiki/Akitu",
 "snippet": "El libreto de la fiesta más importante de Babilonia: el día en que el rey era abofeteado por el sacerdote y el Enuma Elish se recitaba entero ante Marduk.",
 "analysis": "El Enuma Elish no era literatura para leer en silencio sino un texto de culto. El ritual del akītu, la fiesta del Año Nuevo que se celebraba en los primeros días del mes de Nisán, prescribe que el cuarto día, por la tarde, el sumo sacerdote recite el poema de principio a fin ante la estatua de Bel, es decir, de Marduk. Al día siguiente el rey entraba en el santuario, el sacerdote le quitaba las insignias, le abofeteaba y le tiraba de las orejas, y el rey juraba no haber descuidado Babilonia; si al golpe le saltaban las lágrimas era buen augurio. Solo entonces se le devolvía la realeza. La creación del mundo y la renovación del poder se celebraban juntas, cada año, como si el combate contra Tiamat tuviera que volver a ganarse.",
 "history": "Las tablillas que conservan el ritual babilónico del Año Nuevo son copias tardías, de época seléucida, cuando Babilonia ya estaba gobernada por los sucesores de Alejandro; François Thureau-Dangin las publicó juntas en 1921 en sus Rituels accadiens. Que se siguieran copiando siglos después del fin de la monarquía babilónica muestra hasta qué punto el templo mantuvo vivo el culto de Marduk.",
 "bio": "MNB son las siglas del inventario del Musée Napoléon III, el fondo antiguo del departamento de Antigüedades Orientales del Louvre, anterior a la numeración AO. Muchas de sus tablillas llegaron por compra en el siglo XIX, sin excavación documentada."
},
{
 "files": ["06_Tablilla_del_Esagil_Uruk_229aC.jpg"],
 "views": ["Tablilla del Esagil, con las medidas del templo de Marduk — Uruk (229 a.C.)"],
 "title": "La tablilla del Esagil: las medidas de la casa de Marduk",
 "artist": "Uruk, época seléucida (copia fechada en 229 a.C.)",
 "meta": "Arcilla con escritura cuneiforme | Museo del Louvre, París (AO 6555)",
 "wikiUrl": "https://es.wikipedia.org/wiki/Esagila",
 "snippet": "El templo que los dioses construyeron para Marduk al final del Enuma Elish, medido en codos por un escriba: incluye el zigurat que la Biblia llamó Torre de Babel.",
 "analysis": "En la tablilla VI del Enuma Elish, los dioses Anunnaki agradecen a Marduk su victoria construyéndole una casa: moldean ladrillos durante un año entero y levantan el Esagila, «la casa de cabeza alta». Esta tablilla es su contrapartida arquitectónica. Es un texto técnico y matemático que da las dimensiones de los patios del Esagila y del zigurat Etemenanki, «casa del fundamento del cielo y la tierra»: una base cuadrada de unos 90 metros de lado y siete pisos superpuestos. Es la principal fuente escrita para imaginar la torre que el Génesis 11 convierte en símbolo de la soberbia humana.",
 "history": "Según su colofón, se copió en Uruk en el año 83 de la era seléucida, es decir, en 229 a.C., a partir de un original de Borsippa. La publicó Vincent Scheil en 1913, y Andrew George la reeditó en su estudio de la topografía de Babilonia. Las medidas de la base coinciden con los cimientos que Koldewey excavó, aunque la altura real del zigurat sigue siendo discutida.",
 "bio": "Uruk, la ciudad de Gilgamesh, siguió siendo en época seléucida uno de los últimos grandes centros de la cultura cuneiforme, con familias de sacerdotes y escribas que copiaron textos astronómicos, rituales y literarios hasta el siglo I a.C."
},
{
 "files": ["07_Simbolos_de_Marduk_y_Nabu_Estela_de_Bel-harran-beli-usur_750aC.jpg"],
 "views": ["Símbolos de Marduk y Nabu, estela de Bel-harran-beli-usur — Tell Abta (s. VIII a.C.)"],
 "title": "La azada y el cálamo: Marduk y Nabu en una estela asiria",
 "artist": "Tell Abta, estela de Bel-harran-beli-usur (reinado de Tiglat-Pileser III, 744-727 a.C.)",
 "meta": "Relieve en piedra, detalle de estela | Museo del Antiguo Oriente, Museos Arqueológicos de Estambul",
 "wikiUrl": "https://es.wikipedia.org/wiki/Marduk",
 "snippet": "Sin cuerpo ni rostro, solo sus emblemas: así se representaba en el primer milenio al dios que venció al caos.",
 "analysis": "En lo alto de la estela, sobre pedestales, se alzan los símbolos de los dioses que protegen el documento: a la izquierda la marru de Marduk, una azada de hoja triangular; en el centro el cálamo de Nabu, la cuña con la que se escribía el cuneiforme; en el borde derecho asoma la mitad del símbolo de Assur. Mesopotamia prefería a menudo representar a los grandes dioses por sus atributos y no por su figura, y la azada de Marduk resume su papel en el Enuma Elish mejor que un retrato: es el instrumento con el que se abren los canales y se ordena la tierra, lo que Marduk hace con el cuerpo de Tiamat al hacer brotar el Tigris y el Éufrates de sus ojos.",
 "history": "La estela conmemora la fundación de una ciudad por Bel-harran-beli-usur, heraldo de palacio en tiempos de Tiglat-Pileser III (744-727 a.C.). Que un alto funcionario asirio pusiera a Marduk, el dios de Babilonia, en su estela muestra la fuerza de su culto también en el norte, donde los escribas asirios llegaron a copiar el Enuma Elish sustituyendo a Marduk por su propio dios Assur.",
 "bio": "Tell Abta está en la estepa al oeste del Tigris, en el actual Irak. La estela se conserva en el Museo del Antiguo Oriente de Estambul, que reúne las piezas llegadas a la capital cuando Mesopotamia formaba parte del Imperio otomano."
},
{
 "files": ["08_Estela_de_Asurbanipal_Restaurador_del_Esagila_668aC.jpg"],
 "views": ["Estela de Asurbanipal con la cesta de ladrillos — Babilonia (c. 668-655 a.C.)"],
 "title": "Asurbanipal reconstruye la casa de Marduk",
 "artist": "Babilonia, reinado de Asurbanipal (668-c. 631 a.C.)",
 "meta": "Estela de piedra con inscripción cuneiforme | British Museum, Londres (BM 90864)",
 "wikiUrl": "https://es.wikipedia.org/wiki/Asurbanipal",
 "snippet": "El rey de Asiria con una cesta de barro sobre la cabeza, como un obrero: restaura el templo que su abuelo había arrasado.",
 "analysis": "Asurbanipal se hace representar con el gesto más antiguo de la realeza mesopotámica, el del rey constructor que carga en persona la cesta de barro para los cimientos del templo. La inscripción que le rodea explica la obra: la restauración del Esagila, el templo de Marduk en Babilonia. En términos del Enuma Elish es un acto de reparación cósmica, porque el Esagila era la casa que los propios dioses habían construido para Marduk tras vencer a Tiamat, y el lugar donde se recitaba el poema cada Año Nuevo.",
 "history": "Senaquerib, abuelo de Asurbanipal, había arrasado Babilonia en 689 a.C. y llevado la estatua de Marduk a Asiria. Su hijo Esarhaddon inició la reconstrucción y Asurbanipal la continuó, devolviendo la estatua a su templo en 668 a.C., el año en que su hermano Shamash-shum-ukin subió al trono de Babilonia. Una estela casi gemela, con el hermano en el mismo gesto, también está en el British Museum. Veinte años después los dos hermanos se enfrentaron en una guerra civil que terminó con la toma de Babilonia.",
 "bio": "Asurbanipal fue el último gran rey de Asiria y el fundador de la biblioteca de Nínive, de la que procede buena parte del texto del Enuma Elish que se conoce. Su imperio se desmoronó pocos años después de su muerte: Nínive cayó en 612 a.C. ante babilonios y medos."
},
{
 "files": ["09_El_Monstruo_del_Caos_y_el_Dios_Layard_1853.png"],
 "views": ["«El monstruo del caos y el dios» — grabado de Layard, The Monuments of Nineveh (1853)"],
 "title": "La imagen que se tomó por Marduk contra Tiamat",
 "artist": "Austen Henry Layard, a partir de un relieve de Nimrud (1853)",
 "meta": "Grabado, lámina de The Monuments of Nineveh, segunda serie | el relieve, del templo de Ninurta en Nimrud, está en el British Museum",
 "wikiUrl": "https://es.wikipedia.org/wiki/Tiamat",
 "snippet": "Un dios con haces de rayos persigue a un monstruo alado con garras. Durante un siglo fue la ilustración de Marduk y Tiamat; en realidad es otro combate.",
 "analysis": "Un dios alado, con un haz de rayos en cada mano, persigue a una criatura cubierta de plumas, con fauces de fiera, garras de león delante y patas de ave detrás, que se vuelve rugiendo hacia él. La escena es tan cercana a lo que cuenta el Enuma Elish —Marduk armado con el rayo y los vientos contra el monstruo del caos— que los libros de divulgación la usaron durante más de un siglo como la ilustración del combate con Tiamat, y así circula todavía. Pero el relieve procede del templo de Ninurta en Nimrud, y hoy se interpreta como Ninurta persiguiendo a Anzû, el pájaro-león que robó las tablillas del destino. Se incluye aquí precisamente por eso: el poema de Marduk se construyó en parte sobre los mitos de combate de Ninurta, y la confusión moderna repite un préstamo que hicieron los propios babilonios.",
 "history": "Layard excavó Nimrud entre 1845 y 1851 y publicó sus dibujos en dos series de The Monuments of Nineveh (1849 y 1853); las láminas fueron durante décadas la única forma de ver los relieves asirios fuera de Londres. Los relieves de la puerta del templo de Ninurta se enviaron al British Museum. La lectura como Ninurta y Anzû se apoya en el mito de Anzû, cuyo texto no se conoció bien hasta el siglo XX.",
 "bio": "Austen Henry Layard (1817-1894) llegó a Mesopotamia con poco más de veinte años, de camino a Ceilán, y se quedó a excavar. Sus hallazgos en Nimrud y Nínive, y su libro Nineveh and its Remains (1849), un éxito de ventas, hicieron del arte asirio una sensación en la Inglaterra victoriana. Después fue diputado, subsecretario de Asuntos Exteriores y embajador en Madrid y en Constantinopla."
},
]
