{
 "Génesis":("50 capítulos. La colección cubría solo del 1 al 11; la historia patriarcal —el asunto del propio ensayo de la colección— estaba entera vacía.","Cap.",[
  ("1","Creación; el Anciano de los Días","si","Blake"),("1–2","La creación de Adán","si","Miguel Ángel"),
  ("2","La creación de Eva","no","Miguel Ángel, Sixtina — en Commons solo a 1,3 MP"),
  ("2–3","El Edén","si","El Bosco · Cranach · Durero"),("3","La expulsión del Paraíso","si","Masaccio"),
  ("3","Pecado original y expulsión","no","Miguel Ángel, Sixtina — solo 1,4 MP"),
  ("4","Caín y Abel","si","Tiziano · Cormon"),
  ("6–9","El Diluvio","si","Miguel Ángel · Turner · van Scorel · Watts · Danby · Cole"),
  ("9","La embriaguez de Noé","no","Bellini — pendiente"),("11","La Torre de Babel","si","Bruegel · Doré"),
  ("18","La hospitalidad de Abraham","si","Rubliov"),("19","Destrucción de Sodoma","si","John Martin"),
  ("19","Lot y sus hijas","casi","Rubens, Schwerin"),("21","Agar e Ismael","si","Corot"),
  ("22","El sacrificio de Isaac","si","Caravaggio · Rembrandt"),
  ("24","Eliezer y Rebeca","casi","Poussin, Louvre — 70 MP"),("27","Isaac bendice a Jacob","casi","Ribera, Prado"),
  ("28","La escala de Jacob","casi","Ribera, Prado — 680 MP"),
  ("29","Jacob y Raquel en el pozo","no","Palma il Vecchio · Dyce"),
  ("32","La lucha con el ángel","si","Delacroix · Gauguin"),("37","La túnica de José","si","Velázquez"),
  ("37","José vendido por sus hermanos","no","Overbeck · Flavitsky"),
  ("39","José y la mujer de Putifar","no","Rembrandt · Gentileschi"),
  ("49","Jacob bendice a Efraín y Manasés","no","Rembrandt, Kassel")]),
 "La Ilíada":("24 cantos. Están cubiertos el principio, el final y el ciclo troyano ajeno al poema; el centro —los cantos IX, XVI y XVIII— es donde más falta.","Canto",[
  ("previo","El juicio de Paris","si","Rubens, National Gallery"),
  ("previo","El sacrificio de Ifigenia","si","Jacques-Louis David"),
  ("I","Tetis suplica a Zeus","si","Ingres"),("I","Briseida arrebatada a Aquiles","no","Giambattista Tiepolo"),
  ("III","Helena en las murallas","no","en Commons solo a 0,2 MP"),
  ("VI","Héctor y Andrómaca","si","Jacques-Louis David"),
  ("IX","La embajada a Aquiles","no","Ingres, ENSBA — el mayor hueco del poema; en Commons a 0,8 MP"),
  ("X","La Dolonía","si","Casco de colmillos de jabalí"),
  ("XVI","Aquiles llora a Patroclo","si","Gavin Hamilton"),
  ("XVI","La muerte de Sarpedón","casi","Crátera de Eufronio — 42 MP"),
  ("XVIII","Tetis y las armas de Aquiles","casi","Van Dyck, Sanssouci — 75 MP"),
  ("XXII","El triunfo sobre Héctor","si","Franz von Matsch"),
  ("XXIV","Príamo pide el cuerpo de Héctor","si","Alexander Ivanov"),
  ("post.","El caballo de Troya","si","Giandomenico Tiepolo"),("post.","Laocoonte","si","Escuela de Rodas"),
  ("—","Aquiles y Áyax juegan a los dados","si","Exekias"),
  ("arq.","Micenas y Troya","si","Máscara de Agamenón · Puerta de los Leones · Egina · Hisarlik"),
  ("arq.","La copa de Néstor","no","pendiente")]),
 "Gilgamesh":("12 tablillas. Cobertura casi completa para lo que existe: el poema apenas tiene tradición pictórica y su iconografía es arqueológica.","Tablilla",[
  ("I","Las murallas de Uruk","si","Vaso de Warka · Lamassu"),("I","Los sueños de Gilgamesh","si","Tablilla del Sueño"),
  ("II–V","Humbaba y el Bosque de los Cedros","si","Placa babilónica · máscara de terracota"),
  ("VI","Ishtar rechazada","si","Relieve de la Reina de la Noche"),
  ("VI","El Toro Celeste","no","placas de terracota, pendiente"),
  ("—","El héroe y las fieras","si","Relieve de Khorsabad · sello acadio"),
  ("VII–X","La muerte de Enkidu; el inframundo","no","sin obra conocida"),
  ("XI","El Diluvio","si","Tablilla XI, Biblioteca de Asurbanipal")]),
}