{
 "Génesis":("50 capítulos. La colección cubría solo del 1 al 11; la historia patriarcal —el asunto del propio ensayo de la colección— estaba entera vacía.","Cap.",[
  ("1","Creación; el Anciano de los Días","si","Blake"),("1–2","La creación de Adán","si","Miguel Ángel"),
  ("2","La creación de Eva","si","Mural de Narga Selassie, Etiopía"),
  ("2–3","El Edén","si","El Bosco · Cranach · Durero · El Bagawat, Egipto"),("3","La expulsión del Paraíso","si","Masaccio"),
  ("3","Pecado original y expulsión","no","Miguel Ángel, Sixtina — solo 1,4 MP"),
  ("4","Caín y Abel","si","Tiziano · Cormon · Bouguereau, Buenos Aires"),
  ("6–9","El Diluvio","si","Miguel Ángel · Turner · van Scorel · Watts · Danby · Cole · mosaico de Misis · miniatura armenia"),
  ("9","La embriaguez de Noé","no","Bellini — pendiente"),("11","La Torre de Babel","si","Bruegel · Doré"),
  ("18","La hospitalidad de Abraham","si","Rubliov"),("19","Destrucción de Sodoma","si","John Martin"),
  ("19","Lot y sus hijas","casi","Rubens, Schwerin"),("21","Agar e Ismael","si","Corot"),
  ("22","El sacrificio de Isaac","si","Caravaggio · Rembrandt · mosaico de Beit Alfa"),
  ("24","Eliezer y Rebeca","casi","Poussin, Louvre — 70 MP"),("27","Isaac bendice a Jacob","casi","Ribera, Prado"),
  ("28","La escala de Jacob","casi","Ribera, Prado — 680 MP"),
  ("29","Jacob y Raquel en el pozo","no","Palma il Vecchio · Dyce"),
  ("32","La lucha con el ángel","si","Delacroix · Gauguin"),("37","La túnica de José","si","Velázquez"),
  ("37","José vendido por sus hermanos","no","Overbeck · Flavitsky"),
  ("39","José y la mujer de Putifar","si","Behzad, Bustán de El Cairo (1488)"),
  ("49","Jacob bendice a Efraín y Manasés","no","Rembrandt, Kassel")]),
 "La Ilíada":("24 cantos. Están cubiertos el principio, el final y el ciclo troyano ajeno al poema; el centro —los cantos IX, XVI y XVIII— es donde más falta.","Canto",[
  ("previo","El juicio de Paris","si","Rubens, National Gallery"),
  ("previo","El sacrificio de Ifigenia","si","Jacques-Louis David"),
  ("I","Tetis suplica a Zeus","si","Ingres"),("I","Briseida arrebatada a Aquiles","no","Giambattista Tiepolo"),
  ("III","Helena en las murallas","no","en Commons solo a 0,2 MP"),
  ("VI","Héctor y Andrómaca","si","Jacques-Louis David"),
  ("IX","La embajada a Aquiles","no","Ingres, ENSBA — el mayor hueco del poema; en Commons a 0,8 MP"),
  ("X","La Dolonía","si","Casco de colmillos de jabalí"),
  ("XVI","Aquiles llora a Patroclo","si","Gavin Hamilton"),
  ("XVI","La muerte de Sarpedón","casi","Crátera de Eufronio — 42 MP"),
  ("XVIII","Tetis y las armas de Aquiles","casi","Van Dyck, Sanssouci — 75 MP"),
  ("XXII","El triunfo sobre Héctor","si","Franz von Matsch"),
  ("XXIV","Príamo pide el cuerpo de Héctor","si","Alexander Ivanov"),
  ("post.","El caballo de Troya","si","Giandomenico Tiepolo"),("post.","Laocoonte","si","Escuela de Rodas"),
  ("—","Aquiles y Áyax juegan a los dados","si","Exekias"),
  ("arq.","Micenas y Troya","si","Máscara de Agamenón · Puerta de los Leones · Egina · Hisarlik"),
  ("arq.","La copa de Néstor","no","pendiente")]),
 "Éxodo":("40 capítulos. Moisés, las plagas, el mar Rojo y el Sinaí, en manuscritos armenios, persas, hebreos y etíopes, en la pintura europea y en el arte andino.","Cap.",[
  ("2","Moisés salvado de las aguas","si","Rashid al-Din, Edimburgo"),("3","La zarza ardiente","si","Icono del Sinaí"),
  ("7","La vara convertida en serpiente","si","Manuscrito de Shiraz, Berlín"),("7–11","Las plagas de Egipto","si","Hagadá de Oro"),
  ("12","La Pascua","si","Hagadá de las cabezas de pájaro"),("14–15","El paso del mar Rojo","si","Toros Roslin · mural etíope"),
  ("16","El maná","no","Poussin, Louvre: solo foto de sala"),("17","El agua de la roca; Amalec","no","sin imagen utilizable"),
  ("19–20","La Ley en el Sinaí","si","Historias de los profetas · Sinchi Roca, Cusco"),("25–31","El Tabernáculo y el arca","si","Germigny-des-Prés"),
  ("32","El becerro de oro","si","Poussin"),("32–34","Las tablas; el rostro radiante","si","Rembrandt · Miguel Ángel"),
  ("35–40","La construcción del Tabernáculo","no","sin obra")]),
 "Levítico":("27 capítulos. Un libro de leyes y rituales, con pocas escenas: la iconografía es escasa.","Cap.",[
  ("1–7","Los sacrificios","si","Inicial de Cleveland · Corbie, BnF"),("4","Los cuernos del altar","si","Altar de Tel Beerseba"),
  ("8–9","La consagración de Aarón","si","Dura Europos · Santa Sofía de Kiev · Luyken"),("10","Nadab y Abiú","si","Luyken"),
  ("11","Animales puros e impuros","no","solo grabados pobres"),("12–15","Las leyes de pureza","si","Fokke, el leproso"),
  ("16","El chivo expiatorio","si","Holman Hunt"),("17–26","El código de santidad","no","sin obra"),
  ("25","El jubileo","no","sin obra"),("27","Votos y diezmos","no","sin obra")]),
 "Gilgamesh":("12 tablillas. Cobertura casi completa para lo que existe: el poema apenas tiene tradición pictórica y su iconografía es arqueológica.","Tablilla",[
  ("I","Las murallas de Uruk","si","Vaso de Warka · Lamassu"),("I","Los sueños de Gilgamesh","si","Tablilla del Sueño"),
  ("II–V","Humbaba y el Bosque de los Cedros","si","Placa babilónica · máscara de terracota"),
  ("VI","Ishtar rechazada","si","Relieve de la Reina de la Noche"),
  ("VI","El Toro Celeste","no","placas de terracota, pendiente"),
  ("—","El héroe y las fieras","si","Relieve de Khorsabad · sello acadio"),
  ("VII–X","La muerte de Enkidu; el inframundo","no","sin obra conocida"),
  ("XI","El Diluvio","si","Tablilla XI, Biblioteca de Asurbanipal")]),
 "Atrahasis":("3 tablillas, en la versión paleobabilónica del escriba Ipiq-Aya. Casi no tiene iconografía propia: se ilustra con sus dioses, con los textos que comparten su estructura y con los objetos del mundo que describe.","Tablilla",[
  ("I","Los Igigi se rebelan contra el trabajo","no","sin obra conocida"),
  ("I","La creación del hombre con arcilla y sangre divina","no","sin obra conocida — ninguna imagen segura de Nintu/Mami"),
  ("I–II","Enlil y el ruido de los hombres","si","Figura sedente de Enlil, Nippur"),
  ("II","Peste, sequía y hambruna","no","sin obra conocida"),
  ("II–III","Ea avisa a Atrahasis a través de la pared de cañas","si","Ea y los apkallu, pila de Assur"),
  ("III","El Diluvio","si","Tablilla de la Morgan Library · Lista Real Sumeria"),
  ("III","La barca redonda de Atrahasis","no","Tablilla del Arca, British Museum — no hay imagen libre"),
  ("III","El límite a la humanidad: la pāšittu","si","Amuleto de Lamashtu · placa de bronce de Estambul")]),
 "Enuma Elish":("7 tablillas. El poema de la creación de Babilonia; como el Atrahasis, se ilustra con el culto y los símbolos de Marduk más que con escenas.","Tablilla",[
  ("I","Apsu y Tiamat; el nacimiento de los dioses","si","Tablilla de la Biblioteca de Asurbanipal"),
  ("I–III","Tiamat y sus once monstruos","si","Mušḫuššu de la Puerta de Ishtar · copia de Kish"),
  ("IV","Marduk vence a Tiamat","si","Grabado de Layard — en realidad Ninurta y Anzû; falta una imagen segura"),
  ("IV–V","El cielo y la tierra hechos con su cuerpo","no","sin obra conocida"),
  ("VI","La creación del hombre con la sangre de Qingu","no","sin obra conocida"),
  ("VI","Los dioses construyen el Esagila","si","Tablilla del Esagil · estela de Asurbanipal"),
  ("VII","Los cincuenta nombres de Marduk","si","Sello de Marduk y Nabu · estela de Bel-harran-beli-usur"),
  ("—","La recitación en el Año Nuevo","si","Ritual del akītu, Louvre")]),
 "Las lágrimas de Eros":("Las láminas del último libro de Bataille. La cobertura no mide pasajes que falten sino qué láminas se pueden mostrar: 88 con imagen libre y 66 sin ella, por derechos de autor o porque no hay reproducción libre.","Cap.",[
  ("I.1","La conciencia de la muerte: las venus paleolíticas","si","Trasimeno · La Ferrassie · Lespugue · Brassempouy · Laussel · Willendorf · Grimaldi"),
  ("I.1","El Pozo de Lascaux","casi","Escena del Pozo — en Commons solo a 315 px"),
  ("I.2","Trabajo y juego: las cuevas de Trois-Frères; Ain Sakhri","si","Hombre-bisonte · el Hechicero · los amantes de Ain Sakhri"),
  ("II.I","Dioniso o la Antigüedad","si","Delos · monedas de Lete y Tasos · Macrón · Pintor de Pentesilea · Cleofrades · Villa de los Misterios"),
  ("II.II.1","La condena cristiana: el infierno y el Juicio","si","Spranger · Bouts · Van der Weyden · Carpaccio"),
  ("II.II.2","El erotismo vuelve a la pintura","si","Durero · Cranach · Baldung"),
  ("II.II.3","El manierismo","si","Giulio Romano · Gossaert · Bronzino · Correggio · Fontainebleau · Spranger · Zucchi · Tiziano · Caron · Tintoretto"),
  ("II.II.4","El libertinaje del siglo XVIII y Sade","si","Vermeer · Strobel · Picart según Poussin · Rembrandt · Rubens · Füssli"),
  ("II.II.5","Goya","si","Las viejas · la maja desnuda · Caprichos · Disparates · disciplinantes · caníbales · la degollación"),
  ("II.II.6","Gilles de Rais y Erzsébet Báthory","si","Los castillos de Machecoul, Lacoste y Čachtice"),
  ("II.II.7","La evolución del mundo moderno","si","Géricault · Prud'hon · Ingres · Delacroix"),
  ("II.II.8","Delacroix, Manet, Degas, Moreau","si","Manet · Cézanne · Degas · Toulouse-Lautrec · Moreau"),
  ("II.II.8","Los surrealistas","no","Picasso, Ernst, Masson, Delvaux, Magritte, Bellmer, Balthus, Fini, Bacon, Tanning, Klossowski… — derechos vigentes"),
  ("C.2","El sacrificio vudú","no","Fotografías atribuidas a Pierre Verger — derechos vigentes"),
  ("C.3","El suplicio chino","si","Fotografías de Pekín, 1904-1905"),
  ("C.3","Una tradición del horror","si","El Miroir de 1620 · Luyken · Piero di Cosimo")]),
}